### ISSUE TITLE
Windows授权一直无响应，macOS重复授权安装

### ISSUE THREAD

**Issue by Young-3** [goldenduo/AGB#1]
1、Windows初始化后授权一直无响应；macOS重复授权安装，最后会显示失败。
2、使用手机为荣耀9X(系统版本HarmonyOS2.0.0)与小米6(MIUI11.0.5)

**Comment by goldenduo** [comment]
1、手机端需要点“允许安装”
2、如果已经点过允许安装，看起来像是安装失败了，请先尝试手动安装agb/resources目录下agbclient.apk。
3、手头只有MIUI12，无法复现。下个版本我再加些调试日志上去。
4、结果如何麻烦告诉我下，谢谢。

**Comment by Young-3** [comment]
您好
1、macOS 运行agb，手机端可以安装client，并且也显示了应用程序；但是每次点击服务端上的操作按钮，会重新安装客户端。
2、Windows上运行，显示请授权安装，然后一直无反应。
3、手机上已经安装客户端，但是好像隧道建立有问题。

**Comment by goldenduo** [comment]
fixed in version 2
