### ISSUE TITLE
Android12崩溃

### ISSUE THREAD

**Issue by yaoguang** [goldenduo/AGB#10]
Caused by: java.lang.IllegalArgumentException: com.goldenduo.agbclient: Targeting S+ (version 31 and above) requires that one of FLAG_IMM
UTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
06-29 14:04:31.173 19452 19452 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if i
t needs to be used with inline replies or bubbles.

**Comment by goldenduo** [comment]
已经解决，请重新下载
