### ISSUE TITLE
一直提示“请授权安装”“失败”

### ISSUE THREAD

**Issue by weitt159** [goldenduo/AGB#12]
已授权调试权限后，点击连接一直提示“请授权安装”“失败”，且手机没有任何反应。手机型号为mi10ultra，系统为miui13最新开发版内测。

**Comment by goldenduo** [comment]
如下图，确认下USB安装是否已勾选
![image](https://user-images.githubusercontent.com/46618424/178665217-5dd7f06b-8184-4810-809c-cc41dbdd9ab9.png)
