### ISSUE TITLE
群控功能

### ISSUE THREAD

**Issue by q6654282** [goldenduo/AGB#13]
是否有考虑添加群控!单独控制不能支持我的设备了!我设备数量很多!

**Comment by goldenduo** [comment]
> 是否有考虑添加群控!单独控制不能支持我的设备了!我设备数量很多!

能否描述下群控这个功能具体是怎样的？

**Comment by q6654282** [comment]
就是控制一台手机 其他的所有手机同样的操作！

**Comment by q6654282** [comment]
类似于同步器的作用

**Comment by goldenduo** [comment]
明白，AGB项目无此计划，但是[测试猫](https://github.com/goldenduo/TestCat)半年内会添加这个功能。
