### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Naexen** [goldenduo/AGB#14]
https://pastebin.com/sCNmc4MK

**Comment by goldenduo** [comment]
网址点进去空的？

**Comment by Naexen** [comment]
https://pastebin.com/pEYVRaw5
奇怪

**Comment by goldenduo** [comment]
怀疑这个 bug 跟显卡设置有关，可以先重启。

如果重启还是不能启动，就按如下步骤操作：
1、如果是一个显卡，就恢复显卡到出厂设置。
2、如果有两个显卡，一个 Nvidia, 一个 AMD, 在 Nvidia 的显卡设置，找到 G-Sync 相关的设置，并且设置为：只为全屏模式启用 G-Sync 。看能不能正常启动，如果不能，就把 Nvidia 的显卡设置恢复到出厂设置。如果还不能正常启动，就再把 AMD 恢复到出厂设置。
