### ISSUE TITLE
WINDOWS 一直显示授权

### ISSUE THREAD

**Issue by julyiii** [goldenduo/AGB#16]
WINDOWS第一次adb安装软件后,手机会弹出网络vpn授权，之后电脑就一直显示授权中，无法进行网络共享。

**Comment by goldenduo** [comment]
请问重新连接手机，重试可以正常共享网络吗？

**Comment by julyiii** [comment]
还是不可以，会显示这个
![image](https://user-images.githubusercontent.com/95080276/219337728-977e1dc4-ab66-4a1b-8fdf-0ec653b284bd.png)
很期待正常使用您的工具（类似的网络分享不支持ipv6）

**Comment by julyiii** [comment]
使用环境是红米k40,安卓13以及海信a6 安卓8.目测是共性问题。

**Comment by goldenduo** [comment]
麻烦在软件反馈中提交下bug，这样我后台才可能查到日志定位问题。

**Comment by goldenduo** [comment]
部分手机需要在未解锁状态下建立共享网络
