### ISSUE TITLE
能否使用蓝牙共享网络来反向传输？

### ISSUE THREAD

**Issue by h93910** [goldenduo/AGB#2]
环境：Nokia7 原生安卓

现在这边在windows端接了个蓝牙适配器，再使用蓝牙共享让pc与手机在同一网络下
adb tcpip开放端口后，adb connect 成功，AGB上出现图标，点连接后一直处于 请授权安装 的状态，如下图
![image](https://user-images.githubusercontent.com/16130025/145138302-4ffeecaf-b5b7-4d75-8138-8efaad5b6e54.png)

手机端上之前已通过usb线成功共享过网络，即手机已安 agb 的 app

**Comment by goldenduo** [comment]
> 环境：Nokia7 原生安卓
> 
> 现在这边在windows端接了个蓝牙适配器，再使用蓝牙共享让pc与手机在同一网络下
> adb tcpip开放端口后，adb connect 成功，AGB上出现图标，点连接后一直处于 请授权安装 的状态，如下图
> ![image](https://user-images.githubusercontent.com/16130025/145138302-4ffeecaf-b5b7-4d75-8138-8efaad5b6e54.png)
> 
> 手机端上之前已通过usb线成功共享过网络，即手机已安 agb 的 app

理论是可以的，我怀疑因为蓝牙速率太慢安装前要传输agb客户端所以卡在这里，麻烦等待久一点。

**Comment by h93910** [comment]
手机端是已经安装过的了
的确是卡住了，测试等待了半个小时也一直是请授权。看下图我直接usb是秒成功
![image](https://user-images.githubusercontent.com/16130025/145140105-a32c9c65-9231-49cd-af03-0b213f09c600.png)

**Comment by goldenduo** [comment]
fixed in version 2
