### ISSUE TITLE
关于红米K50U的连接问题

### ISSUE THREAD

**Issue by leocoln** [goldenduo/AGB#21]
使用设备为红米K50U，系统为MIUI13.0.3
已经打开开发者选项/USB调试/USB安装/USB调试（安全设置） （USB安全设置打开后允许通过USB调试修改权限或模拟点击）
只顺利连通过一次，可以对手机进行操控，但后续都显示OFFLINE，右方按钮只有“使用电脑网络”“投射手机屏幕”而没有“播放手机声音”
点击“投射手机屏幕”会显示设备不在线。

**Comment by goldenduo** [comment]
怀疑是因为连接手机后，弹出USB调试授权的按钮没有及时授权，默认是不授权导致的。多次不授权后系统会跳过这个授权提醒直接offline。这种情况可以尝试重启手机再连接试试，记得及时授权。麻烦告诉我们尝试的结果，谢谢。

**Comment by leocoln** [comment]
尝试步骤如下：
1、使用原厂的数据线连接，有充电提示，并且弹出“仅充电”“传输数据(mtp)”“传输图片”选择，而后弹出“允许usb调试吗？ 这台计算机的rsa密钥指纹如下：（略）”，默认勾选一律允许使用计算机进行调试。
2、先取消“一律允许使用计算机进行调试”，然后点击确定。软件显示离线，右方只有“使用电脑网络”“投射手机屏幕”按钮，点击投射手机屏幕按钮后提示设备不在线。
3、拔开数据线后再次连接，依然有充电提示，弹出三个模式的选择，而后弹出“允许ubs调试吗”，默认勾选一律允许使用计算机进行调试。
4、勾选“一律允许使用计算机进行调试”，点击确定软件显示离线，右方只有“使用电脑网络”“投射手机屏幕”按钮，点击投射手机屏幕按钮后提示设备不在线。

我个人推测有可能是电脑的问题，晚点尝试换一个设备进行测试。

**Comment by goldenduo** [comment]
是的，这种情况怀疑你电脑上有什么流氓软件强制占用了你手机的调试功能，只能关闭相关软件。
