### ISSUE TITLE
代码不见了? project 404?

### ISSUE THREAD

**Issue by History-exe** [goldenduo/AGB#5]
项目是被放弃了吗，无程序下载。

**Comment by goldenduo** [comment]
> 项目是被放弃了吗，无程序下载。

你好，项目还在维护中，刚试了mac跟windows的链接都可以下载哦。
建议切换换下网络重试。

**Comment by History-exe** [comment]
OK，了解了。谢谢回复。
哈哈，我想下载的就是linux的

**Comment by goldenduo** [comment]
哦哦，linux用户太少，暂时还不打算维护linux版本。
