### ISSUE TITLE
linux版本404

### ISSUE THREAD

**Issue by shenmo7192** [goldenduo/AGB#8]
linux版本404了

**Comment by goldenduo** [comment]
#5 linux用户少所以暂时没有版本

**Comment by shenmo7192** [comment]
> #5 linux用户少所以暂时没有版本

不过目前也只有Linux用户刚需这个了，因为别的替代品不支持ipv6
Windows下有很多选择了

**Comment by goldenduo** [comment]
> > #5 linux用户少所以暂时没有版本
> 
> 不过目前也只有Linux用户刚需这个了，因为别的替代品不支持ipv6
> Windows下有很多选择了

嗯嗯，感谢反馈，之后我会考虑加上，不过近来比较忙，可能迟一些。请问windows下有哪些可选择的产品？我想下载看看。

**Comment by shenmo7192** [comment]
> > > #5 linux用户少所以暂时没有版本
> > 
> > 
> > 不过目前也只有Linux用户刚需这个了，因为别的替代品不支持ipv6
> > Windows下有很多选择了
> 
> 嗯嗯，感谢反馈，之后我会考虑加上，不过近来比较忙，可能迟一些。请问windows下有哪些可选择的产品？我想下载看看。

https://www.zhihu.com/question/390137908
整合的有一些手机助手还有搞机工具箱

Linux下目前只有Genymobile的方案了
