### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by CVKNO80098** [goldenduo/AGB#9]
这是咋回事
![image](https://user-images.githubusercontent.com/88498956/175193921-697eb99c-b43c-46a0-a3ca-7e6481530320.png)
简介上说可以IPv4连接，可以说一下方法吗

**Comment by CVKNO80098** [comment]
这是咋回事
![image](https://user-images.githubusercontent.com/88498956/175193921-697eb99c-b43c-46a0-a3ca-7e6481530320.png)
简介上说可以IPv4连接，可以说一下方法吗

**Comment by goldenduo** [comment]
你好，方便提供下是什么操作系统，什么语言环境吗。 连接网络的话，只需要打开安卓手机调试模式，usb连接手机，点击下面按钮。
<img width="407" alt="image" src="https://user-images.githubusercontent.com/46618424/175198986-49f976fd-61df-4401-bd25-8c394b5716d1.png">
